[build-system]
requires = ["setuptools>=61.0", "tcod==14.0.0"]
build-backend = "setuptools.build_meta"

[project]
name = "starstranded_ryou"
version = "0.3.2"
authors = [
  { name="Ryou", email="ryou.takeshi@gmail.com" },
]
description = "A roguelike survival game set on an alien planet."
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]